package co.fy.core.server.OauthAccessToken.model;

public class OauthAccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.authentication_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    private String authenticationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.token_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.user_name
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.client_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.refresh_token
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    private String refreshToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.authentication_id
     *
     * @return the value of oauth_access_token.authentication_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public String getAuthenticationId() {
        return authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.authentication_id
     *
     * @param authenticationId the value for oauth_access_token.authentication_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.token_id
     *
     * @return the value of oauth_access_token.token_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.token_id
     *
     * @param tokenId the value for oauth_access_token.token_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.user_name
     *
     * @return the value of oauth_access_token.user_name
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.user_name
     *
     * @param userName the value for oauth_access_token.user_name
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.client_id
     *
     * @return the value of oauth_access_token.client_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.client_id
     *
     * @param clientId the value for oauth_access_token.client_id
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.refresh_token
     *
     * @return the value of oauth_access_token.refresh_token
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.refresh_token
     *
     * @param refreshToken the value for oauth_access_token.refresh_token
     *
     * @mbggenerated Tue Dec 05 09:45:41 CST 2017
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }
}