package co.fy.core.server.organization.dao;

import co.fy.core.server.organization.model.Organization;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class OrganizationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public String insertSelective(Organization record) {
        BEGIN();
        INSERT_INTO("organization");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getAddtime() != null) {
            VALUES("addtime", "#{addtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeletetime() != null) {
            VALUES("deletetime", "#{deletetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnable() != null) {
            VALUES("enable", "#{enable,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public String updateByPrimaryKeySelective(Organization record) {
        BEGIN();
        UPDATE("organization");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getAddtime() != null) {
            SET("addtime = #{addtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDeletetime() != null) {
            SET("deletetime = #{deletetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEnable() != null) {
            SET("enable = #{enable,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return SQL();
    }
}