package co.fy.core.server.organization.model;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.addtime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.deletetime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    private Date deletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.enable
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.addtime
     *
     * @return the value of organization.addtime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.addtime
     *
     * @param addtime the value for organization.addtime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.deletetime
     *
     * @return the value of organization.deletetime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public Date getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.deletetime
     *
     * @param deletetime the value for organization.deletetime
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.enable
     *
     * @return the value of organization.enable
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.enable
     *
     * @param enable the value for organization.enable
     *
     * @mbggenerated Mon Dec 18 17:22:06 CST 2017
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}